import os, zipfile, re

mods_dir = r"C:/Users/Administrator/Documents/My Games/FarmingSimulator2025/mods"
TARGETS = [
 "WheelPhysics.serverUpdate","WheelPhysics.finalize","WheelPhysics.updatePhysics",
 "WheelPhysics.updateTireFriction","WheelPhysics.updateFriction","WheelPhysics.updateWheelFriction",
 "WheelPhysics.updateContact","WheelsUtil.updateWheelsPhysics","WheelsUtil.updateWheelsPhysicsGroundContact",
 "WheelsUtil.getSmoothedAcceleratorAndBrakePedals","Drivable.updateVehiclePhysics",
 "Motorized.updateConsumers","Motorized.onUpdate","Motorized.getMaxPtoRpm",
 "Motorized.getUseAutomaticGearShifting","Motorized.getUseAutomaticGroupShifting",
 "Vehicle.update","Vehicle.updateTick","Vehicle.onUpdate","Vehicle.load","Vehicle.getSpeedLimit",
 "FSBaseMission.update","FSBaseMission.sendInitialClientState","FSBaseMission.onConnectionFinishedLoading",
 "Sprayer.processSprayerArea","Cutter.onEndWorkAreaProcessing",
 "BunkerSilo.update","BunkerSilo.load","BunkerSilo.loadFromXMLFile",
 "PlayerHUDUpdater.showSplitShapeInfo","PlayerHUDUpdater.showFieldInfo",
 "ConstructionBrush.verifyAccess","Farm.changeBalance","InfoDialog.show",
 "VehicleMaterial.apply","VehicleMaterial.applyToVehicle",
 "PlaceableProductionPoint.onFinalizePlacement","ProductionPoint.load",
 "DensityMapHeightManager.loadMapData","Weather.update",
]

from collections import defaultdict
_METHOD_TARGETS = defaultdict(list)
for _t in TARGETS:
    _METHOD_TARGETS[_t.split(".",1)[1]].append(_t)

def hooks(blob, klass, meth):
    ce = re.escape(klass); me = re.escape(meth)
    # all CLASS-AWARE: Class.method = Utils.xFunction  /  = function  /  Utils.xFunction(Class.method  /  Class["method"] = Utils
    if re.search(ce+r"\."+me+r"\s*=\s*Utils\.(overwritten|appended|prepended)Function", blob): return True
    if re.search(ce+r"\."+me+r"\s*=\s*function", blob): return True
    if re.search(r"Utils\.(overwritten|appended|prepended)Function\s*\(\s*"+ce+r"\."+me, blob): return True
    if re.search(ce+r"\[\s*['\"]"+me+r"['\"]\s*\]\s*=\s*Utils\.(overwritten|appended|prepended)Function", blob): return True
    # SpecializationUtil.register{Overwritten,Appended,Prepended}Function(vehType, "meth", impl)
    # — spec overwrites call Utils.*Function under the hood, so they surface in our
    # registry (deferred → "(unknown)"). Only trust for methods UNIQUE across TARGETS
    # (class is a variable here, so a common name like "update" would cross-attribute).
    if len(_METHOD_TARGETS[meth]) == 1:
        if re.search(r"register(Overwritten|Appended|Prepended)Function\s*\(\s*\w+\s*,\s*['\"]"+re.escape(meth)+r"['\"]", blob):
            return True
    return False

hookmap = {t: [] for t in TARGETS}
zips = [f for f in os.listdir(mods_dir) if f.endswith(".zip")]
for fn in zips:
    mod = fn[:-4]
    try:
        with zipfile.ZipFile(os.path.join(mods_dir, fn)) as z:
            blob = ""
            for e in z.namelist():
                if e.endswith(".lua"):
                    try: blob += z.read(e).decode("utf-8","ignore")
                    except: pass
            if "Utils." not in blob: continue
            for t in TARGETS:
                k,m = t.split(".",1)
                if hooks(blob,k,m): hookmap[t].append(mod)
    except: pass

out = ["-- mm_hookmap_generated.lua  (auto-generated by gen_hookmap.py)",
       "-- target -> { installed mods that STATICALLY hook it } (class-aware match).",
       "-- Used for scan-elimination naming of deferred '(unknown)' hooks: debug is",
       "-- unavailable in-game, so this is the only attribution path. Excludes the mod",
       "-- itself. Regenerate (gen_hookmap.py) whenever the installed mod set changes.",
       "ModMixerHookMap = {"]
for t in TARGETS:
    mods = sorted(set(m for m in hookmap[t] if m != "FS25_0_ModMixer"))
    if not mods: continue
    out.append('    ["%s"] = { %s },' % (t, ", ".join('"%s"'%m for m in mods)))
out.append("}")
txt = "\n".join(out)+"\n"
open(r"B:/Farm Sim Mod Dev/FS25_ModMixer/FS25_ModMixer/scripts/mm_hookmap_generated.lua","w",encoding="utf-8").write(txt)
print(f"scanned {len(zips)} zips\n")
print(txt)
